### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by kubatatami** [yusukeinouehatchout/scroll_to_id#1]
Thanks for the great package!

Do you plan to make a null safe update of the package?

**Comment by domzinhuu** [comment]
i need know too!

**Comment by nazarrd** [comment]
please make a null safe update to this great package

**Comment by jamesneve** [comment]
https://github.com/yusukeinouehatchout/scroll_to_id/pull/2

If anyone still wants a nullsafe version of this package, you can use my branch. I did pull request, but not sure if this library is still maintained...

**Comment by yusukeinouehatchout** [comment]
Merged #2

Thanks!
